# Generated by Django 4.1.3 on 2022-11-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="real_price",
            field=models.FloatField(default=0, verbose_name="real price"),
        ),
    ]
