# Generated by Django 4.1.3 on 2022-12-07 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.brandmodel",
                verbose_name="brand",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.categorymodel",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="color",
            field=models.ManyToManyField(
                related_name="products", to="product.colormodel", verbose_name="color"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="size",
            field=models.ManyToManyField(
                related_name="products", to="product.sizemodel", verbose_name="size"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="tag",
            field=models.ManyToManyField(
                related_name="products", to="product.tagmodel", verbose_name="tag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistmodel",
            unique_together={("user", "product")},
        ),
    ]
