# Generated by Django 4.1.3 on 2022-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("address_2", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.PositiveIntegerField()),
                ("phone", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=254)),
                ("total_price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "order",
            },
        ),
    ]
