# Generated by Django 4.1.3 on 2022-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="products",
            field=models.ManyToManyField(
                related_name="order", to="product.productmodel"
            ),
        ),
    ]
